---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.01.2020 23:24
---
function Face()
	local face = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)--Create a new frame of Type BACKDROP
	BlzFrameSetSize(face, 0.015, 0.015)
	BlzFrameSetAbsPoint(face, FRAMEPOINT_BOTTOM, 0.65, 0.0065)
	BlzFrameSetTexture(face, "ReplaceableTextures\\CommandButtons\\BTNHeroPaladin",0, true)--face uses paladin blp as texture.

	face = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)--Create a new frame of Type BACKDROP
	BlzFrameSetSize(face, 0.015, 0.015)
	BlzFrameSetAbsPoint(face, FRAMEPOINT_BOTTOM, 0.695, 0.0065)
	BlzFrameSetTexture(face, "ReplaceableTextures\\CommandButtons\\BTNHeroPaladin",0, true)--face uses paladin blp as texture.

end